name: 'Setup Dinghy'
description: 'Setup Dinghy for use in GitHub Actions workflows'

inputs:
  prepare-images:
    description: 'list of images to prepare in advance'
    required: false
    default: 'release'

outputs:
  dinghy-version:
    description: 'The version of Dinghy CLI that was installed'
    value: ${{ steps.install-dinghy-cli.outputs.dinghy-version }}

runs:
  using: 'composite'
  steps:
    - name: Install Dinghy CLI
      id: install-dinghy-cli
      shell: bash
      run: |

        echo "::group::Install Dinghy CLI"
        DINGHY_VERSION="${DINGHY_CLI_VERSION:-0.0.0}"
        if [ "$DINGHY_VERSION" = "0.0.0" ]; then
          if [ -f ".dinghyrc" ]; then
            while IFS= read -r line || [ -n "$line" ]; do
              case "$line" in
                DINGHY_ENGINE_VERSION=*)
                  DINGHY_VERSION="${line#DINGHY_ENGINE_VERSION=}"
                  break
                  ;;
              esac
            done < ".dinghyrc"
          fi  
          if [ "$DINGHY_VERSION" != "0.0.0" ]; then
            export DINGHY_VERSION="$DINGHY_VERSION"
          fi
        fi
        curl -fsSL "https://get.dinghy.dev/install.sh?source=github-action&version=$DINGHY_VERSION" | sh
        export PATH="$HOME/.dinghy/bin:$PATH"
        echo "::endgroup::"
        
        echo "::group::Prepare Images"
        PREPARE_IMAGES="${{ inputs.prepare-images }}"
        dinghy docker cache --include-images $PREPARE_IMAGES
        echo "::endgroup::"
        
        echo "::group::Prepare Workflow"
        dinghy gh prepare
        echo "::endgroup::"

