name: 'Install Dinghy CLI'
description: 'Install Dinghy CLI for use in GitHub Actions workflows'

inputs:
  prepare-images:
    description: 'list of images to prepare in advance'
    required: false
    default: 'release'

outputs:
  dinghy-version:
    description: 'The version of Dinghy CLI that was installed'
    value: ${{ steps.install-dinghy-cli.outputs.dinghy-version }}

runs:
  using: 'composite'
  steps:
    - name: Install Dinghy CLI
      id: install-dinghy-cli
      shell: bash
      run: |

        echo "::group::Install Dinghy CLI"
        curl -fsSL https://get.dinghy.dev/install.sh | sh
        export PATH="$HOME/.dinghy/bin:$PATH"
        echo "::endgroup::"
        
        echo "::group::Prepare Images"
        PREPARE_IMAGES="${{ inputs.prepare-images }}"
        dinghy docker cache --include-images $PREPARE_IMAGES
        echo "::endgroup::"
        
        # Set outputs
        FULL_VERSION=$(dinghy --version)
        DINGHY_VERSION=$(echo "$FULL_VERSION" | sed -n 's|@dinghy/cli/\([^ ]*\) .*|\1|p')
        echo "dinghy-version=${DINGHY_VERSION}" >> $GITHUB_OUTPUT
        echo "$HOME/.dinghy/bin" >> $GITHUB_PATH

